# Generated by Django 5.0.4 on 2024-04-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EsGratuito', models.BooleanField(default=False)),
                ('FechaYHoraDeCreacion', models.DateTimeField(auto_now_add=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.IntegerField()),
                ('NombreDeProducto', models.TextField(max_length=100)),
                ('TiempoDeCreacion', models.TimeField()),
            ],
        ),
    ]
