# Generated by Django 5.0.4 on 2024-04-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='TiempoDeCreacion',
        ),
    ]
