# Generated by Django 5.0.4 on 2024-04-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_products_tiempodecreacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='EsGratuito',
            new_name='esGratuito',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='FechaYHoraDeCreacion',
            new_name='fecha_hora',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='NombreDeProducto',
            new_name='nombre_producto',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Stock',
            new_name='stock',
        ),
    ]
